services:
  alembic:
    build: .
    command: alembic upgrade head      
    volumes:
      - .:/app
    networks:
      - ok_network


  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - alembic
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - ok_network


  test:
    build: .
    command: pytest --maxfail=3 --disable-warnings
    depends_on:
      - alembic
    networks:
      - ok_network
    volumes:
      - .:/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app



networks:
  ok_network:
    external: true
